apiVersion: v1
kind: Service
metadata:
  name: simple-go-api-service
spec:
  selector:
    app: simple-go-api
  ports:
  - port: 7001
    protocol: TCP
    targetPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-api-nodeport
spec:
  type: NodePort
  ports:
  - port: 7001
    nodePort: 7001
  selector:
    app: simple-go-api
