name: release
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry Run'
        required: true
        type: boolean
        default: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{vars.CI_GO_VERSION}}
#      - name: my-step
#        if: ${{ inputs.dry-run == false }}
#        run: echo "Hello World! false condition met"
#      - name: check-flag
#        run: |
#          if ${{ inputs.dry-run == true }}; then
#            echo "feature enabled"
#          else
#            echo "NOT enabled"
#          fi
      - name: Create Tag
        run: |
          # install svu to calculate next semver version
          go install github.com/caarlos0/svu/v2@v2.0.1
          git tag $(svu next)
      # go releaser
      - name: Test
        run: go test -v ./...
      - name: Telease
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean ${{ inputs.dry-run && '--skip=publish' || '' }}
          workdir: ./cmd/http
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
